[package]
name = "mongodb001"
version = "0.1.0"
authors = ["南沢郁男 <fmsoft@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb ="0.9.0"
bson = "0.14.0"
